### ISSUE TITLE
Is the input_dataset.csv file available?

### ISSUE THREAD

**Issue by BakingBrains** [RodMech/OSNet-IBN1-Lite#2]
Where can I get the input_dataset.csv file

**Comment by RodMech** [comment]
@BakingBrains Hello, sorry but I have no samples available, but they are regular pictures. You can tweak the input handler by yourself. What I mention in the README is just an example. 

You just need to provide the features to the encoder as shown below:

`df["feature_vector"] = encoder.get_features(list(df["uncompressed_feature_vector"]))`

If you want to keep the same format, try to generate a dataframe with a column named `uncompressed_feature_vector`, and paste there a picture in a hexadecimal string format. Follow the guidelines and If you need further guidance, let me know.

**Comment by BakingBrains** [comment]
Thank you so much
